# Generated by Django 3.1.6 on 2021-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='model', max_length=225)),
                ('summary', models.TextField()),
                ('model_file', models.FileField(null=True, upload_to='ai_models')),
                ('category', models.IntegerField(choices=[(1, 'image'), (2, 'text'), (3, 'nlp'), (4, 'video'), (5, 'others')], default='image')),
                ('model_image', models.ImageField(null=True, upload_to='ai_models/images')),
            ],
        ),
    ]
