# Generated by Django 3.1.6 on 2021-06-08 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_auto_20210521_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='model', max_length=225)),
                ('Email', models.EmailField(default='model', max_length=225)),
                ('Subject', models.CharField(default='model', max_length=225)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelEditForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='model', max_length=225)),
                ('summary', models.TextField()),
                ('model_file', models.FileField(null=True, upload_to='ai_models')),
                ('category', models.IntegerField(choices=[(1, 'image'), (2, 'text'), (3, 'nlp'), (4, 'video'), (5, 'others')], default='image')),
                ('model_image', models.ImageField(null=True, upload_to='ai_models/images')),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
